### ISSUE TITLE
Annotating alignment positions in the CIGAR string.

### ISSUE THREAD

**Issue by javh** [airr-community/airr-formats#26]
To perform proper germline reconstruction from alignment data we'll need to be able to extract the following information from the CIGAR string:

* Alignment start position in the query (input) sequence.
* Alignment start position in the reference (subject) sequence.
* Alignment end position in the query (input) sequence.
* Alignment end position in the reference (subject) sequence.
* Location of any indels in the query or reference.

I'm not seeing a good way to encode the end positions in the CIGAR string other than deriving them from the alignment length. Maybe we want to re-open discussion on whether we should use end or length in a separate issue?

For the start position, I think we can encode that as missing characters in the alignment. There are several different ways to encode missing characters in an alignment and they all seem to have different meanings (`P`, `H`, `S` and `D`). As near as I can tell, it seems like the most appropriate way to encode what we want is by using `P` for the reference start position and `S` for the query start.

For example, take an alignment with:

* CIGAR string = `30M1I69M3D50M`
* Query start = 5. The first 4 bases are not in the alignment against the reference (they are "soft clipped").
* Reference start = 17. The 5th base of the query aligns to position 17 in the reference (the reference is "padded").

The resultant CIGAR would then be:

`16P4S30M1I69M3D50M`

Assuming we mandate that `P` annotations must always precede `S` annotations in the CIGAR string. Which is another thing to decide.

We'd then have to calculate query/reference end positions by walking through the CIGAR strings like so:

* Adding `S`, `X`, `=`, `M` and `I` lengths to derive the query end.
* Adding `P`, `X`, `=`, `M` and `D` lengths to derive the reference end.

I have a working implementation to derive this information from CIGAR and BTOP strings in [changeo.Parsers](http://changeo.readthedocs.io/en/airr-format/modules/Parsers.html) (`decodeBTOP`, `decodeCIGAR`, `encodeCIGAR`, `alignmentPositions`, `padAlignment`). But, I'm not entirely certain I've understood and implemented it correctly.

Thoughts? Corrections?

**Comment by schristley** [comment]
Where are you looking for CIGAR documentation? I've been mostly looking at the [SAM spec](https://samtools.github.io/hts-specs/SAMv1.pdf) for the description. According to their table (page 6), they list which codes "consume" the query and/or reference. `S` looks good from that perspective because it consumes the query and thus can indicate the start. `P` indicates that neither the query nor the reference are consumed, so I'm thinking it's not the right letter. `N` looks better because it consumes the references (without tagging it as a deletion like with `D`).

**Comment by javh** [comment]
I'm using mostly the SAM spec and [this wiki](http://davetang.org/wiki/tiki-index.php?page=SAM). `N` appears to be used exclusively for introns, by convention, but I'm not sure.

* `N` = Skipped region from the reference
* `P` = Padding (silent deletion from the padded reference sequence)
* `S` = Soft clip on the read (clipped sequence present in input sequence)
* `H` = Hard clip on the read (clipped sequence NOT present in input sequence)

`N` and `D` are apparently indistinguishable in an alignment, so they just differ by conventional use.

**Comment by schristley** [comment]
Yeah, there seems to be an implicit assumption with the SAM spec that the query string completely aligns from the start to end, thus `N` is only used internally for introns. But its description seems pretty clear with "skipped region from the reference". In the examples, `P` seems to be used for padding when you have multiple reads aligning with different gaps, apparently without the `P` you cannot disambiguate between various alignments.

**Comment by javh** [comment]
Hrm. I'm looking over it again and it *seems* like `N ~ D` and `P ~ I` are equivalent. So `N` would represent bases missing in the input sequence, not bases missing from the reference. Yes?

**Comment by schristley** [comment]
Technically they are similar, though no exact, but they also have different semantics.

For `P` and `I`, take a look at the padded alignment example in that wiki. For read1, it uses `I` to indicate that "consumes from query" is happening, but for read2, `P` is used because neither the query or reference are consumed. However, for us, `P` and `I` look the same because we aren't doing any multiple alignments like in that example, so we might use `I` for everything to indicate an insertion.

For `N` and `D`, the difference seems to be semantic. While both "consume from reference", `D` is meant to indicate an actual deletion (thus implying a mutation event) while `N` is meant to just skip reference sequences, e.g. with an intron.

My thought was that 'N' versus `D` is appropriate for skipping the beginning of the reference sequence because those sequences are being skipped without implying some mutation event, i.e. the cause is really just because the read starts in the middle. `D` makes sense in the middle of the read sequence because it is a deletion.

Same idea applies to `I` in that it implies a mutational event, while appropriate in the middle of the read sequence, it might not be correct for the beginning. Skipping query sequences at the beginning or end maybe due to the read starting/ending before/after the start of the V gene, though this is probably rare to see, but still it shouldn't be semantically tagged as an insertion event, thus why I was thinking `S` was more appropriate.

**Comment by javh** [comment]
What we need to be able to represent are both of these cases:

```
Reference:   -----ATGCCC  | start=5
Query:            ATGCCC  | start=0
```
```
Reference:   -----ATGCCC  | start=5
Query:     GGGGGGGATGCCC  | start=7
```

**Comment by schristley** [comment]
The dashes in the reference represent the IMGT gaps in the germline? Maybe treat them like introns, so for the first case `N5` in cigar will skip the 5 dashes in the reference.

The second case is odd, there is nothing to the left of the dashes in the reference? The combination of `N5` and `S7` should work though.

**Comment by javh** [comment]
Kind of. The dashes are just there to indicate where the alignment starts in the reference relative to the full reference sequence. In the end, we would need this information to fill in the reference with such gaps to adhere to the IMGT numbering scheme and make sure the reference and query are properly aligned in the output.

As I understand it, `N5` would look like:
```
Reference:      GGGGGATGCCC  | start=0
Query:          NNNNNATGCCC  | start=5
```

A deletion from the query, not a deletion from the reference.

**Comment by schristley** [comment]
Okay, according to the SAM spec, the start position in the reference is given as a separate field versus being encoded into the CIGAR string, and as I mentioned above it's assumed the starting position in the query is 1.

> 4. POS: 1-based leftmost mapping POSition of the first CIGAR operation that “consumes” a reference base (see table below). The first base in a reference sequence has coordinate 1. POS is set as 0 for an unmapped read without coordinate. If POS is 0, no assumptions can be made about RNAME and CIGAR.

We can do the same thing, have a field that indicates the start in the germline (v_start?), and we likely also need to indicate the start in the reference. Or we can encode into the CIGAR string. Because we are going somewhat outside the SAM spec, I think we can use the codes

`N` consumes from reference, not query, so `N5` does not change the "current" position in the query sequence, it stays at the start=0 point, it only moves the position forward on the reference, so I believe it looks like this:

```
Reference:   GGGGGATGCCC  | pos=5
Query:            ATGCCC  | pos=0
```

**Comment by javh** [comment]
Hrm. I feel like we are mixing up our words somehow. "Consumes the reference" sounds like "advances the position in the reference", which generates a deletion annotation in the query within the alignment. 

This is the `N` example from the wiki:

*In cDNA-to-genome alignment, we may want to distinguish introns from deletions in exons. We introduce openation 'N' to represent long skip on the reference sequence. Suppose the spliced alignment is:*

```
REF: AGCTAGCATCGTGTCGCCCGTCTAGCATACGCATGATCGACTGTCAGCTAGTCAGACTAGTCGATCGATGTG
READ:          GTGTAACCC................................TCAGAATA
```

*where `...` on the read sequence indicates intron. The CIGAR for this alignment is : `9M32N8M`.*

To reconstruct the alignment you have to walk through the CIGAR making changes to the query as indicated, so:

1. Take the first 9 bases of the query
2. Insert 32 gaps.
3. Take the next 8 bases of the query.

**Comment by javh** [comment]
Wait... I think I'm confusing myself. So you're saying `N5` and `0S` gives:

```
Reference:   -----ATGCCC  | start=5
Query:            ATGCCC  | start=0
CIGAR:       NNNNNMMMMMM
```

Yes?

**Comment by javh** [comment]
Heh. Okay, @schristley I'm reading back through everything and I *think* we are on the same page now. It just wasn't clicking for me and I think you're right.

Let's go with `N` for the reference start position.

**Comment by schristley** [comment]
Yes, exactly, the CIGAR string would `5N6M`.

That is assuming we don't have a separate field that specifies the start in the reference. However, let's say we had that like in the SAM spec, then:

```
ref_start = 5
```

(or ref_start=4 for 0-based I guess) and the CIGAR string would just be `6M`

**Comment by laserson** [comment]
If I understand correctly, and as @schristley points out above, the CIGAR string itself is not enough...we also need to have a coordinate in the reference to specify where the alignment should begin.  It looks like you can solve this, then, by reporting a "global" alignment with `N`s which eliminates the need for the extra field?  (i.e., ref and query alignments always start at 0)  That sounds good to me.

Separately, are we to expect that reference sequences will be padded in the style of IMGT?  I never actually did this myself, and figured getting IMGT numbering was a totally separate pass on the reads.

**Comment by javh** [comment]
No, I don't think we are expecting reference sequences to be IMGT-gapped. It is a separate pass. We just need all these little alignment details to make that second pass.

**Comment by javh** [comment]
Finalized on `S` for query start and `N` for reference start in 7761181.
