### ISSUE TITLE
Minimal Standard "Study" vs Formats "Project"

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-formats#31]
Hi Scott,
I was looking at your YAML spec (specs/study.yaml) for the AIRR Minimal Standards and I noticed that the Minimal Standards group uses "Study" based terminology but in your YAML file you use "Project". 

There are three fields that are the primary conflicts:
- study in Minimal Standard VS project in the YAML file.
- study_title in Minimal Standards VS project_title in the YAML file.
- study_type in Minimal Standards VS project_type in the YAML file. 

Any rationale on why the difference???

Brian

**Comment by schristley** [comment]
I'm not sure why it's different. The AIRR column in the Minimal Standards spreadsheet has project, project_title, project_type so those were likely just copied over directly in the YAML, even though the descriptions in the spreadsheet say study.

On a side note, I see that Ahmad has created a repository for minimal standards. I had created those YAML files because earlier minimal standards wasn't going to put their stuff into git, but thankfully that has changed. I think those YAML files should move to the minimal standards repository.

https://github.com/airr-community/airr-standards

**Comment by bcorrie** [comment]
Hi Scott,

In documenting the API and looking at the AIRR  terminology, I am pretty sure these should be "study" not "project". Minimal Standards has no concept of a "project". In the API Spec I am going with study_title and study_type 8-)

BTW, Minimal Standards now has a CSV file that is fairly minimal. It would be nice if we could add a "computable name" column that is the AIRR format equivalent to this:

https://github.com/airr-community/airr-standards/blob/master/AIRR_Minimal_Standard_Data_Elements.csv

**Comment by schristley** [comment]
I’m good with “study” over “project”. The CSV file does seem to have an “AIRR Formats WG designation” column which is our computable name, though I see there are a few fields that have not been assigned.

**Comment by schristley** [comment]
I'm waiting for Ahmad to give me access to the airr-standards repository. I have the changes you suggested sitting in my local git waiting to be pushed.

**Comment by bcorrie** [comment]
User (loser) error on my part 8-) I didn't see the column to the right with the WG designation information on my screen as the left/right scroll bar is right at the bottom 8-(

This looks good...

**Comment by schristley** [comment]
all done
