### ISSUE TITLE
reference implementation

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-formats#4]
I previously created a vdj-standard repository with a template python package for a reference implementation for the standard. Should we continue the route of having a separate repository or should we merge and just have a single one? For example, I think each reference implementation should read in the yaml file versus each implementation having its own copy. Maybe we can use git's submodules to organize, any suggestions?

I'd like to see multiple implementations, at least python and javascript are of interest to me, and maybe it's easier (building, packaging, etc.) if each was in its own repository?

**Comment by schristley** [comment]
_Some thoughts I gathered up from email exchange_

I don’t really see the parsers as being part of the spec, they are essentially just “things we need”. The reference implementation just becomes a small library for reading/writing the data format. Now technically, anybody can manually write out the format but library can offer some encapsulation and validation procedures. The reference implementation (for python) should be its own repository, and we should make it like any standard python package.

Here’s what I’m seeing as in initial interface. I’m thinking an OO class, thus these are instance methods. The first design decision is that the data is too large so it should be a streaming interface, read/write one record at a time.

create(filename)
open(filename)
close()

Next design is how to handle the metadata and header stuff, which needs to be at the beginning of the file. I’d like us to follow the PROV standard for provenance (https://www.w3.org/TR/prov-dm) in the metadata, at least for the files and tools, and we can be specialized with the entities and activities we support. There is also a provenance model for dictionary structures (https://www.w3.org/TR/2013/NOTE-prov-dictionary-20130430/) which we can consider for tools that add columns, extend the data format, or even just put in data, but let’s hold off on that at first.

For entities, I see

1. input sequence file to the VDJ rearrangement tool
2. Germline database
3. The output from the VDJ rearrangement tool
4. The VDJ rearrangement tool itself
5. The parser of the VDJ rearrangement tool output into the data standard
6. The data standard output file
7. Annotation tool (of which there will be many)
8. Auxiliary files used by annotation tools

For the activities, I see

1. Execution of the VDJ rearrangement tool
2. Execution of the parser
3. Execution of an annotation tool

I’m not sure how we handle agents, e.g. Person running the code, or this could be VDJServer. I don’t see this as critical to reproduction of the analysis though so it’s optional. The activities have attributes that define info about the execution, command-line arguments, etc.

We then have the relations (these become mandatory for the format spec)

- #E3 wasDerivedFrom #E1, #A1 Used #E2 and #E4, #E3 WasGeneratedBy #A1, (optionally) WasAssociatedWith agent
- #E6 wasDerivedFrom #E3, #A2 Used #E5, #E6 WasGeneratedBy #A2, (optionally) WasAssociatedWith agent

Additional relations are created as annotation tools add info, technically the input and output should be different entities, and also different activity #’s

#E6 wasDerivedFrom #E6, #A3 Used #E7 and (optionally) #E8, #E6 WasGeneratedBy #A3, (optionally) WasAssociatedWith agent

So based upon this, I say we have some specific functions

addRearrangementTool(#E1, #E2, #E3, #E4, #A1)
addParserTool(#E5, #A2)
addAnnotationTool(#E7, #A3, #E8, namespace)
…plus some accessor methods

Then metadata about the columns

columnNames()
addColumns(namespace, names)

Lastly the row methods. We have two design choices here for the row data structure, the first is to transform the row into a dictionary, or alternatively keep the row as an array with a dictionary that maps names to array indexes. The former adds transformation overhead while the latter could potentially be faster if going to access the same columns over and over (I.e. Tools cache the array index)

createRow(dictionary)
readRow()
writeRow()
setRowValue(dictionary)

The other thing we want to consider are the column names. Should we define constants for all of the well-defined columns in the data standard (id, sequence, etc.), or users just use the defined string names (‘id’, ‘sequence’, etc)?  If we use constants (actually well-defined instance variable names), then we can have very efficient code to access the data. Each row is left as an array, and the constant gets defined to the proper array index when the metadata headers are read.

row[airr.id], row[airr.sequence], etc.

Of course we could do the same thing where the underlying row data structure is a dictionary.

**Comment by laserson** [comment]
I have to catch up on the email exchange, but two quick points:

- strictly speaking, by using TSV and YAML, we don't need to specify anything for parsers since we're using totally standard formats that pretty much every language already implements.

- I imagine we can ship "reference implementations" for Python and R, which are likely the most commonly used languages for analyzing this data.  For Python, this could mean a pip-installable package that provides the schema itself so you can check whether you have all the necessary columns etc.  (E.g., you can imagine a function that takes a pandas data frame as input and tells you whether it's valid or not).  We can do the same for R data.frames.

After that, I would think people should be free to construct their TSV files however they like (but most likely with data frames).  The outstanding issue would be related to the metadata.  I'm not sure whether pandas/R has a standard way to allow you to dump some headerlines, but I'd be surprised if it's not possible.  We could also have a function that checks whether the metadata is compliant (with our as-of-yet unspecified metadata requirements).

Finally, I'd vote that the Python/R/js impls be implemented in this repository.  This way we can have a release process that ties everything together.  If a change is made to the YAML, it will push new artifacts to PyPI, CRAN, etc.

**Comment by schristley** [comment]
The parser I'm referring to is the tool that parses the VDJ rearrangement output, e.g. Change-O's MakeDB parsing IgBlast output. If a VDJ rearrangement tool outputs this data format directly then there is no parser.

**Comment by schristley** [comment]
Regarding the repository setup, I'm thinking each implementation is in its own repository, but they can all be linked into this one with git's submodules? Or are you suggesting that they should all reside in the same repository?  I think that makes it messy for versioning, automated generation of packages/docker images, etc. I would like each implementation to pull the YAML spec from here but I'm not sure how to do that...

**Comment by laserson** [comment]
I am suggesting that all the different tools we write for validation all live in this repository.  (See the [Avro repo](https://github.com/apache/avro/tree/master/lang) for an example of this kind of thing.)  Ideally, the VDJ rearrangement tools will output our AIRR format as the default (eventually), so in my mind, compatibility/parsing should rest on their shoulders.

I guess I see two possible functions:

- *validation*: checking that input/output appears to conform to our YAML-spec

- *conversion*: converting between other formats and our format

I'd say that *validation* code can live here, and generate artifacts in PyPI, CRAN, npm, etc., so that tool-builders can easily import our library to check that they're in compliance.  This code should be tightly coupled to our YAML-spec, and so I'd vote that it live here.

I'd say that the *conversion* code should ideally live with the respective tools, but perhaps that could be put into a separate repo?

**Comment by schristley** [comment]
Okay, that works. If we build a docker image, it can just install everything for all of the languages, instead of having a separate image for each.

I agree that it would be nice for the VDJ rearrangement tools to output AIRR format, but I'm more interested in the broader goal of provenance and reproducibility. I'd like to design the metadata to handle this up front. So I'm thinking of the reference library as more than just validation, but also provide the generation of the format.

Now I understand that some people won't care about provenance/reproducibility, and they are just gonna throw away the metadata and manually parse the TSV. But I'd much prefer that to be the exception versus rule, thus why I want it to an automatic part of the reference implementation. For those of us funded by the NIH, losing that provenance is gonna bite us in the ass down the road...

**Comment by schristley** [comment]
I've pushed an initial reference library for python. It reads the yaml spec though doesn't do much with it yet. I played around with basic idea of storing provenance for tools that either create an initial rearrangements file or create a derived file where additional annotation is added.

**Comment by laserson** [comment]
@schristley, thanks for putting this together!  I just looked through the code a bit and mainly have one comment. Since we're essentially writing TSV files, my preference would be to use the most popular TSV reader for python: pandas.  I'd guess that most analysis will take place using pandas (or should).  Then we can have a minimal verifier that ensures that the columns that pandas parses are correct and have the correct types.

I'm gonna try to take a crack at a PR with a bit of cleanup, and will send out for review.

**Comment by schristley** [comment]
I'm not familiar with pandas, but if it offers type-checking and can handle the marshaling back/forth between text and internal types, then that is good.

**Comment by laserson** [comment]
bumping this wrt setting up change-o integration to @javh

**Comment by laserson** [comment]
In an effort to clean up, I am closing this for now, as I'm not certain what the action is here.  We should hopefully be discussing reference impls on our calls more in the lead up to the December meeting.
