### ISSUE TITLE
Change "sequence_id" to "rearrangement_id"?

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-formats#46]
Makes it clearer that a rearrangement may not correspond to a single physical read.

**Comment by javh** [comment]
I think it's to denote that it's the id of the read in the `sequence` column. I'd prefer just `id`.

**Comment by laserson** [comment]
Yes, but is it not ever the case that the `sequence` is actually a consensus derived from multiple raw reads?

**Comment by schristley** [comment]
I don't like plain `id` because it is too generic, id of what? I gave it the name `sequence_id` just as Jason indicated, it is the id of the read in the `sequence` column. That extra little bit of semantics helps and also make the field name unique across all AIRR schema objects.

We could have an additional `rearrangement_id` field, in theory this could be the GenBank accession number, but we won't always have that number available. If we add it then tools will have to make up a value for the field, inducing questions like is it globally unique? If it is only unique within a file, what if files are combined?

**Comment by schristley** [comment]
We never resolved the issue of how to represent multiple sequences into the same rearrangement. One of the proposals was for sequence_id to be a list, but we nixed that. And thus we are left with this ambiquity.

**Comment by laserson** [comment]
I think one way to solve it is to have a key from the alignment table to the rearrangement table.  All the raw sequencing reads are aligned and probably represented in the alignment table.  Then we do some magic and spit out a beautiful analysis-ready rearrangement table.

**Comment by schristley** [comment]
From our `VDJPipe` tool, sequences have to be identical (same length and nt) to be collapsed, and so the `sequence` is identical for all reads and thus just pick one of the `sequence_id`, it doesn't exactly matter. The `duplicate_count` tells you how many of them. This may not be true for other tools though.

**Comment by javh** [comment]
Yeah, `sequence` can be a consensus from multiple reads. As I understood it, `sequence` is whatever was input into the alignment tool, with `sequence_id` being the identifier for the input.

I don't think it's bad that `id` is ambiguous, because it reflects the identifier of the alignment (output), the identifier of the input, and the mapping to the hit table entries. It's our "row key". At least, that's how I was thinking of it.

**Comment by schristley** [comment]
I think that is reasonable, we can define the alignment table however we want, so it can point into the rearrangement table. I think we can reuse the `sequence_id` for that though instead of creating an additional `rearrangement_id`, each entry in the alignment table has foreign `sequence_id` field.

**Comment by schristley** [comment]
But yeah `sequence_id` has the wrong semantics then, so I like `rearrangement_id` better. There is no reason that tools can't just use the read id for that.

**Comment by schristley** [comment]
The problem with the field name being just `id` is that it can cause problems downstream. We have multiple WGs who are creating entities, relationships between them, APIs, and etc., and if everybody called their fields `id` for each entity then it just makes a mess. If `id` was internal to our file then okay, but our rearrangement format is becoming core to much of AIRR WG efforts.
