### ISSUE TITLE
sample_id should be pointing to a NucleicAcidProcessing object

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-formats#48]
The `sample_id` should essentially be pointing to a "sequencing library", including all the info about the processing (e.g., sorted on a CD19 etc).  Bc there can be multiple repertoires form a single blood draw

**Comment by schristley** [comment]
The `definitions.yaml` file has a `nucleic_acid_processing_id` field though the minimal standards doesn't show any of the primary/foreign keys in their spreadsheet other than for study, subject and sample. `nucleic_acid_processing_id` is only unique within a study.

**Comment by javh** [comment]
Correct me if I'm wrong, but I don't think any of the field names in the minimal standards document are official.  The minimal data standards elements are descriptive only, at this point.

Maybe we should consider some sort of formal structure to the grouping of field names? Eg, all study associated fields being with `study_`, biological sample fields with `sample_`, library prep with `library_`, etc?

**Comment by schristley** [comment]
They aren't official in that there was a vote or anything, but Christian and Ahmad have been updating them as the minimal standards is being cleaned up, plus you have iReceptor, VDJServer and very soon common repository WG using them in specs and APIs, so they are quickly becoming semi-official.

I think they somewhat avoid the `study_` and `sample_` etc for all fields because they wanted to use field names that match NCBI common data elements. It's debatable if that's the best idea, but there you have it...

**Comment by schristley** [comment]
I think they are going to all stay semi-official until the minimal standards WG does all the ontology/controlled vocabulary work, which will actually define the semantics for the fields.

**Comment by javh** [comment]
Ah, okay. Well, maybe we should make this a topic for a call? I feel kinda blind without some clear guidelines.

**Comment by schristley** [comment]
Sorry Jason, didn't mean for you to be left out of the loop. It's only really started to be addressed by WGs just the past couple weeks, and accelerated because iReceptor and VDJServer are trying to finish major implementations to demo at Dec. AIRR meeting. We (iReceptor, VDJServer) could have just done _whatever_ but both have high-level mandates to be "AIRR-compliant", whatever that means, so a lot of new design is being injected. The implementations have raced past the WGs...

**Comment by javh** [comment]
Well, I guess if everything is implemented with sufficient abstraction then renaming fields later should be trivial.

We should also discuss whether we can/should design these fields with the intention of using them in [GenBank structured comments](https://www.ncbi.nlm.nih.gov/genbank/structuredcomment). This is one of the things that came up when working through the AIRR minimal information GenBank submission process. It's something we can add to the submissions, if we want, but we need to have a clearly defined vocabulary to give NCBI so that they can parse it and tag the data as AIRR.

**Comment by laserson** [comment]
I believe the initial issue derived from my misunderstanding the MiAIRR schema.  It seems they had accidentally misrepresented a couple things in their original figure.  I think this is a non-issue now.  I think pointing at the biosample ID is probably fine, as there should be a 1:1 correspondence with the SRA experiment.

@javh's GB comment is now #51.
