### ISSUE TITLE
Consider renaming "rearrangements" to "chains"?

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-formats#49]
Two different heavy chains could be in theory the same biological "rearrangement" but obviously would refer to a different heavy chain sequence.  Perhaps a more accurate name would be "chain" or "annotated chain"?

This just came out of a conversatoin with Bjoern in which it was a bit confusing what exactly we meant.  In reality, each row in our file is a complex aggregate of some raw reads.

**Comment by schristley** [comment]
That opens the question of how to represent paired chains. With paired sequencing, you get both chains, would we want to report this as two rows (which then requires a link between the rows), or would we add additional columns to represent the paired VDJ? Because there is a finite number of chains in a rearrangement, I'd probably prefer additional columns purely from a computational perspective for tools, but that's hypothetical.

Note that minimal standards is using `cell_index` so they are proposing multiple rows with a link. But we don't have to follow that, as our rearrangements can be normalized into multiple rows for GenBank submission.

**Comment by laserson** [comment]
My main concern is that any given cell could in principle have even more than two chains associate with it, and it seems like doubling or tripling the columns would be an awkward fit for this (and the naming scheme would be awkward too, as it would probably have to be parsed).  To me, adding a row and connecting with a `cell_index` is most in line with the principle of least surprise.

**Comment by javh** [comment]
I agree. Having a `cell_index` column seems the most robust.

**Comment by laserson** [comment]
We'll stick with "rearrangements" for now following our call.
